import test from 'node:test';
import assert from 'node:assert/strict';
import {QUESTIONS} from '../public/data.js';
import {total} from '../public/scoring.js';
import {learningProfile,newAdaptive,selectedExercises,adaptiveSummary,validateAdaptive} from '../public/adaptive-core.js';
import {createService} from '../netlify/lib/service.js';
const attemptsFor=n=>Object.fromEntries(QUESTIONS.map((q,i)=>[q.id,i<n?[q.answer]:[Array.isArray(q.answer)?[...q.answer].reverse():(q.answer+1)%q.options.length,q.answer]]));
function memory(){const data=new Map();let n=0;return {async get(k){return structuredClone(data.get(k)?.data||null)},async getWithMetadata(k){return structuredClone(data.get(k)||null)},async setJSON(k,d,o={}){const old=data.get(k);if(o.onlyIfNew&&old||o.onlyIfMatch&&old?.etag!==o.onlyIfMatch)return {modified:false};data.set(k,{data:structuredClone(d),etag:String(++n)});return {modified:true}},async list({prefix}){return {blobs:[...data.keys()].filter(k=>k.startsWith(prefix)).map(key=>({key}))}},async delete(k){data.delete(k)}};}
test('Laluan menggunakan ketepatan pertama, dengan sempadan 9/10/15/16 dan bukan mata ulangan',()=>{for(const [n,route]of [[0,'pemulihan'],[9,'pemulihan'],[10,'pengukuhan'],[15,'pengukuhan'],[16,'pengayaan'],[20,'pengayaan']]){const p=learningProfile(attemptsFor(n));assert.equal(p.first,n);assert.equal(p.route,route);assert.equal(p.ready,true);assert.equal(selectedExercises(p).length,3);}assert.equal(total(attemptsFor(0)),60);assert.equal(newAdaptive({}),null);});
test('Pemilihan mengutamakan kemahiran lemah; bantuan dan draf tidak mengubah laluan',()=>{const attempts=attemptsFor(10),p=learningProfile(attempts),q=selectedExercises(p),r=newAdaptive(attempts);assert.equal(q[0].skill,p.weakest[0]);r.hints.push(q[0].id);r.tries[q[0].id]=[(q[0].answer+1)%q[0].options.length,q[0].answer];assert.equal(validateAdaptive(r,attempts).route,'pengukuhan');assert.equal(adaptiveSummary(r,attempts).solved,1);assert.equal(adaptiveSummary(r,attempts).firstPractice,0);});
test('Pelayan menolak laluan palsu, pengubahan sejarah, jawapan luar bank dan penyiapan palsu',()=>{const a=attemptsFor(20),r=newAdaptive(a),qs=selectedExercises(learningProfile(a));assert.throws(()=>validateAdaptive(r,{}));assert.throws(()=>validateAdaptive({...r,route:'pemulihan'},a));assert.throws(()=>validateAdaptive({...r,ids:['wrong']},a));assert.throws(()=>validateAdaptive({...r,tries:{wrong:[0]}},a));assert.throws(()=>validateAdaptive({...r,tries:{[qs[0].id]:[99]}},a));r.tries[qs[0].id]=[qs[0].answer];assert.throws(()=>validateAdaptive({...r,tries:{}},a,r));assert.throws(()=>validateAdaptive({...r,submitted:true},a));for(const q of qs)r.tries[q.id]=[q.answer];assert.equal(adaptiveSummary(r,a).complete,false);r.draft={mode:'lisan',situation:'Buku berselerak.',action:'Aina menyusun buku.',proverb:'Ringan tulang',reason:'Dia rajin membantu.'};r.submitted=true;const saved=validateAdaptive(r,a);assert.equal(adaptiveSummary(saved,a).complete,true);assert.match(adaptiveSummary(saved,a).status,/perlu semakan guru/);assert.throws(()=>validateAdaptive({...saved,submitted:false},a,saved));assert.deepEqual(validateAdaptive(undefined,a,saved),saved);});
test('Naik taraf sesi: rekod lama kekal, latihan dihantar, idea hanya pada ruang guru, kelas ditutup menolak kemajuan baharu',async()=>{const teacherKey='kunci-guru-untuk-ujian',run=createService(memory(),{teacherKey});const room=await run({action:'create',teacherKey,name:'Kelas lama'}),p=await run({action:'join',code:room.code,name:'Aina',car:'red'}),a=attemptsFor(20),send={action:'progress',code:room.code,id:p.id,token:p.token,attempts:a,reflections:{habit:'help'}};await run(send);let t=await run({action:'teacher',teacherKey,code:room.code});assert.equal(t.rows[0].score,100);assert.equal(t.rows[0].adaptive,null);const r=newAdaptive(a);for(const q of selectedExercises(learningProfile(a)))r.tries[q.id]=[q.answer];r.draft={mode:'tulis',situation:'Sekolah',action:'Mengemas',proverb:'Ringan tulang',reason:'Rajin membantu'};r.submitted=true;await run({...send,adaptive:r});await run(send);t=await run({action:'teacher',teacherKey,code:room.code});assert.deepEqual(t.rows[0].adaptive,r);assert.equal(t.rows[0].reflections.habit,'help');const b=await run({action:'leaderboard',code:room.code});assert.equal(b.rows[0].adaptive,undefined);assert.equal(b.rows[0].attempts,undefined);await run({action:'close',teacherKey,code:room.code});const changed=structuredClone(r);changed.draft.reason='Bukti baharu';await assert.rejects(run({...send,adaptive:changed}),e=>e.status===409);await run(send);});
