import test from 'node:test';
import assert from 'node:assert/strict';
import {createService,validateAttempts} from '../netlify/lib/service.js';
import {LEVELS,QUESTIONS,PROVERBS} from '../public/data.js';
import {grade,total,rankRows} from '../public/scoring.js';
function memory(){const data=new Map();let version=0;return {async get(k){return structuredClone(data.get(k)?.data||null);},async getWithMetadata(k){return structuredClone(data.get(k)||null);},async setJSON(k,d,o={}){const old=data.get(k);if(o.onlyIfNew&&old||o.onlyIfMatch&&old?.etag!==o.onlyIfMatch)return {modified:false};const etag=String(++version);data.set(k,{data:structuredClone(d),etag});return {modified:true,etag};},async list({prefix}){return {blobs:[...data.keys()].filter(k=>k.startsWith(prefix)).map(key=>({key}))};},async delete(k){data.delete(k);}};}
const key='kunci-guru-untuk-ujian';
test('Skor 100; cuba lagi 3 mata; bonus tidak mengubah skor utama',()=>{const a=Object.fromEntries(QUESTIONS.map(q=>[q.id,[q.answer]]));assert.equal(total(a),100);a.l1q1=[1,0];assert.equal(total(a),98);a.b1=[0];assert.equal(total(a),98);assert.equal(grade(QUESTIONS[0],[]),0);assert.equal(LEVELS.length,4);assert.equal(PROVERBS.length,5);});
test('Seri berkongsi kedudukan; belum tamat tidak diberi ranking',()=>{const rows=rankRows([{name:'Z',score:88,done:true},{name:'A',score:94,done:true},{name:'B',score:88,done:true},{name:'C',score:100,done:false}]);assert.deepEqual(rows.map(x=>x.rank),[1,2,2,null]);});
test('Pengesahan jawapan menolak data palsu dan pindaan sejarah',()=>{assert.throws(()=>validateAttempts({l1q1:[9]}));assert.throws(()=>validateAttempts({l1q1:[0,1]}));assert.throws(()=>validateAttempts({l2q5:[[1,1,1]]}));assert.throws(()=>validateAttempts({l1q1:[0]},{l1q1:[1]}));assert.throws(()=>validateAttempts({wrong:[0]}));assert.doesNotThrow(()=>validateAttempts({l1q1:[1,0]},{l1q1:[1]}));});
test('Sesi, dua peserta, pengasingan token, skor pelayan, refleksi, tutup dan padam',async()=>{const run=createService(memory(),{teacherKey:key});await assert.rejects(run({action:'create',teacherKey:'wrong'}),e=>e.status===401);const room=await run({action:'create',teacherKey:key,name:'3 Cemerlang'});const a=await run({action:'join',code:room.code,name:'Aina',car:'red'});const b=await run({action:'join',code:room.code,name:'Ravi',car:'teal'});const attempts=Object.fromEntries(QUESTIONS.map(q=>[q.id,[q.answer]]));await assert.rejects(run({action:'progress',code:room.code,id:a.id,token:b.token,attempts}),e=>e.status===401);const progress=await run({action:'progress',code:room.code,id:a.id,token:a.token,attempts,score:99999,reflections:{strength:'baca',difficulty:'alasan',strategy:'read',habit:'help'}});assert.equal(progress.score,100);assert.equal(progress.done,true);const publicBoard=await run({action:'leaderboard',code:room.code});assert.equal(publicBoard.rows.length,2);assert.equal(publicBoard.rows[0].rank,1);assert.equal(publicBoard.rows[1].rank,null);assert.equal(publicBoard.rows[0].tokenHash,undefined);assert.equal(publicBoard.rows[0].reflections,undefined);const teacher=await run({action:'teacher',code:room.code,teacherKey:key});assert.equal(teacher.rows[0].reflections.habit,'help');await run({action:'close',code:room.code,teacherKey:key});await assert.rejects(run({action:'join',code:room.code,name:'Mira',car:'red'}),e=>e.status===409);await assert.rejects(run({action:'progress',code:room.code,id:b.id,token:b.token,attempts}),e=>e.status===409);await run({action:'open',code:room.code,teacherKey:key});await run({action:'progress',code:room.code,id:b.id,token:b.token,attempts,reflections:{}});const tied=await run({action:'leaderboard',code:room.code});assert.deepEqual(tied.rows.map(x=>x.rank),[1,1]);await run({action:'delete',code:room.code,teacherKey:key});await assert.rejects(run({action:'leaderboard',code:room.code}),e=>e.status===404);});
test('Kunci guru diperlukan; kod sesi dan refleksi disahkan',async()=>{const run=createService(memory());assert.equal((await run({action:'health'})).teacherReady,false);await assert.rejects(run({action:'create',teacherKey:'anything'}),e=>e.status===503);await assert.rejects(run({action:'leaderboard',code:'../../x'}));});
