// Pelayan ujian setempat. Data sesi simulasi disimpan dalam memori sahaja.
import http from 'node:http';
import {readFile} from 'node:fs/promises';
import path from 'node:path';
import {createService} from '../netlify/lib/service.js';
const memory=new Map();let revision=0;
const store={async get(k){return structuredClone(memory.get(k)?.data||null);},async getWithMetadata(k){return structuredClone(memory.get(k)||null);},async setJSON(k,data,options={}){const old=memory.get(k);if((options.onlyIfNew&&old)||(options.onlyIfMatch&&old?.etag!==options.onlyIfMatch))return {modified:false};const etag=String(++revision);memory.set(k,{data:structuredClone(data),etag});return {modified:true,etag};},async list({prefix}){return {blobs:[...memory.keys()].filter(k=>k.startsWith(prefix)).map(key=>({key}))};},async delete(k){memory.delete(k);}};
const dispatch=createService(store,{teacherKey:process.env.KUNCI_GURU||'guru-ujian-tempatan'});
const root=path.resolve('public');const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png','.webp':'image/webp','.mp3':'audio/mpeg','.woff2':'font/woff2'};
http.createServer(async(req,res)=>{try{if(req.url==='/.netlify/functions/classroom'&&req.method==='POST'){let raw='';for await(const c of req){raw+=c;if(raw.length>24000){res.writeHead(413);res.end();return;}}try{const result=await dispatch(JSON.parse(raw));res.setHeader('Content-Type','application/json');res.end(JSON.stringify(result));}catch(e){res.writeHead(e.status||500,{'Content-Type':'application/json'});res.end(JSON.stringify({error:e.message}));}return;}const file=path.resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname==='/'?'/index.html':new URL(req.url,'http://localhost').pathname));if(!file.startsWith(root+path.sep)){res.writeHead(403);res.end();return;}res.setHeader('Content-Type',mime[path.extname(file)]||'application/octet-stream');const bytes=await readFile(file);res.setHeader('Accept-Ranges','bytes');const range=req.headers.range?.match(/^bytes=(\d+)-(\d*)$/);if(range){const start=Number(range[1]),end=Math.min(range[2]?Number(range[2]):bytes.length-1,bytes.length-1);if(start> end){res.writeHead(416,{'Content-Range':`bytes */${bytes.length}`});res.end();return;}res.writeHead(206,{'Content-Range':`bytes ${start}-${end}/${bytes.length}`,'Content-Length':end-start+1});res.end(bytes.subarray(start,end+1));}else{res.setHeader('Content-Length',bytes.length);res.end(bytes);}}catch{res.writeHead(404);res.end('Tidak ditemui');}}).listen(Number(process.env.PORT)||4173,'127.0.0.1',()=>console.log('Pratonton http://127.0.0.1:'+(process.env.PORT||4173)+' · Sesi kelas ialah simulasi tempatan.'));
